import {test,expect} from '@playwright/test';
import {join} from 'node:path';
import {tmpdir} from 'node:os';

const signedOut={schemaVersion:1,source:'companion-live',remaining:null,quotaState:'signed-out',tasksState:'unsupported',tasks:[],notice:'',quotaLabel:'账户额度',quotaWindows:[],authState:'signed-out',canAuthorize:true,canDisconnect:false};
const packet={schemaVersion:2,source:'companion-live',sequence:1,applications:[{id:'codex',iconMode:'brand',state:{schemaVersion:1,source:'companion-live',sequence:1,remaining:49,quotaState:'ready',tasksState:'ready',tasks:[]}},...['cursor','claude','grok-bot','zcode','kimi','doubao-work','workbuddy'].map(id=>({id,iconMode:'brand',state:{...signedOut,...(['cursor','claude','grok-bot'].includes(id)?{}:{quotaState:'unsupported',authState:'unsupported',canAuthorize:false})}}))]};

test('打开才显示、关闭选中项后回退、重开不抢选择、全部关闭为空',async({page})=>{
  const errors=[];page.on('pageerror',error=>errors.push(error.message));page.on('console',message=>{if(message.type()==='error')errors.push(message.text());});
  await page.setViewportSize({width:390,height:844});
  await page.addInitScript(data=>{
    window.__PULSE_HOST_MODE__='live';
    const listeners=new Set(),sent=[];
    window.__pulseTest={sent,send:value=>listeners.forEach(listener=>listener({data:value}))};
    window.chrome={webview:{addEventListener:(_,fn)=>listeners.add(fn),removeEventListener:(_,fn)=>listeners.delete(fn),postMessage:message=>{sent.push(message);if(message.type==='ready')setTimeout(()=>window.__pulseTest.send({type:'snapshot',value:data}),0);if(message.type==='pin')window.__pulseTest.send({type:'pinned',value:message.value});}}};
  },{...packet,applications:packet.applications.slice(0,1)});
  await page.goto('/systems/pulse-desktop/desktop/index.html');
  await expect(page).toHaveURL(/\/systems\/pulse-desktop\/desktop\/index.html$/);
  await expect(page).toHaveTitle('Pulse · 应用状态');
  await expect(page.locator('.pd-summary')).toHaveCount(1);
  await expect(page.locator('.pd-summary')).toHaveAttribute('data-application','codex');
  await expect(page.locator('.pd-pages')).toHaveCount(0);
  const anchor=await page.locator('.pd-rail').boundingBox();
  let sequence=1;
  const present=async ids=>page.evaluate(data=>window.__pulseTest.send({type:'snapshot',value:data}),{...packet,sequence:++sequence,applications:packet.applications.filter(app=>ids.includes(app.id))});
  await present(['codex','cursor']);
  await expect(page.locator('.pd-summary')).toHaveCount(2);
  const expandedAnchor=await page.locator('.pd-rail').boundingBox();
  expect(expandedAnchor.x).toBe(anchor.x);expect(expandedAnchor.y).toBe(anchor.y);
  await page.locator('.pd-summary[data-application="cursor"]').focus();await page.keyboard.press('Enter');
  await page.getByRole('button',{name:'固定面板',exact:true}).click();
  await expect(page.locator('.pd-panel h2')).toHaveText('Cursor');
  await present(['codex']);
  await expect(page.locator('.pd-summary')).toHaveCount(1);await expect(page.locator('.pd-panel h2')).toHaveText('Codex');
  await present(['codex','cursor']);
  await expect(page.locator('.pd-panel h2')).toHaveText('Codex');
  await present(['cursor']);
  await expect(page.locator('.pd-summary')).toHaveCount(1);await expect(page.locator('.pd-panel h2')).toHaveText('Cursor');
  await expect(page.locator('.pd-summary[data-application="codex"]')).toHaveCount(0);
  await present([]);await expect(page.locator('.pd-dock')).toHaveCount(0);
  await present(['codex']);await expect(page.locator('.pd-summary')).toHaveCount(1);
  await expect(page.locator('.pd-panel h2')).toHaveText('Codex');
  await page.getByRole('button',{name:'收起面板',exact:true}).click();
  await expect(page.locator('.pd-dock')).toHaveAttribute('data-mode','compact');
  await page.mouse.move(380,700);
  await page.locator('.pd-dock').screenshot({path:join(tmpdir(),'pulse-presence-only-open.png')});
  await expect(page.locator('vite-error-overlay')).toHaveCount(0);expect(errors).toEqual([]);
});

for(const viewport of [{width:1440,height:900},{width:390,height:844}])test(`独立授权状态、应用分页和只读边界 ${viewport.width}`,async({page})=>{
  const errors=[];page.on('pageerror',error=>errors.push(error.message));page.on('console',message=>{if(message.type()==='error')errors.push(message.text());});
  await page.setViewportSize(viewport);
  await page.addInitScript(data=>{
    window.__PULSE_HOST_MODE__='live';
    const listeners=new Set(),sent=[];
    window.__pulseTest={sent,send:value=>listeners.forEach(listener=>listener({data:value}))};
    window.chrome={webview:{addEventListener:(_,fn)=>listeners.add(fn),removeEventListener:(_,fn)=>listeners.delete(fn),postMessage:message=>{sent.push(message);if(message.type==='ready')setTimeout(()=>window.__pulseTest.send({type:'snapshot',value:data}),0);if(message.type==='pin')window.__pulseTest.send({type:'pinned',value:message.value});}}};
  },packet);
  await page.goto('/systems/pulse-desktop/desktop/index.html');
  await expect(page).toHaveTitle('Pulse · 应用状态');
  await expect(page.locator('.pd-summary')).toHaveCount(3);
  await page.locator('[data-application="cursor"].pd-summary').focus();await page.keyboard.press('Enter');
  await expect(page.locator('.pd-panel h2')).toHaveText('Cursor');
  await expect(page.locator('.pd-panel')).toContainText('任务状态、关注和完成通知尚未接入');
  await page.getByRole('button',{name:'固定面板',exact:true}).click();
  await expect(page.locator('.pd-account')).toContainText('无需重复登录');
  await page.getByRole('button',{name:'备用网页登录',exact:true}).click();
  expect(await page.evaluate(()=>window.__pulseTest.sent.filter(message=>message.type==='authorize'))).toEqual([{type:'authorize',applicationId:'cursor'}]);
  const update=async(state,sequence)=>page.evaluate(({packet,state,sequence})=>window.__pulseTest.send({type:'snapshot',value:{...packet,sequence,applications:packet.applications.map(app=>app.id==='cursor'?{...app,state:{...app.state,...state}}:app)}}),{packet,state,sequence});
  await update({authState:'authorizing',quotaState:'authorizing',notice:'请在官方页面登录'},2);
  await expect(page.getByRole('button',{name:'备用网页登录',exact:true})).toHaveCount(0);
  await page.getByRole('button',{name:'取消登录',exact:true}).click();
  expect(await page.evaluate(()=>window.__pulseTest.sent.some(message=>message.type==='cancel-authorization'&&message.applicationId==='cursor'))).toBe(true);
  await update({authState:'error',quotaState:'error',notice:'登录已超时，请重试'},3);
  await expect(page.locator('.pd-panel')).toContainText('登录已超时');
  await expect(page.getByRole('button',{name:'备用网页登录',exact:true})).toBeVisible();
  await update({authState:'error',quotaState:'error',authorizationBlocked:true,canDisconnect:true,notice:'凭据损坏，请先断开'},4);
  await expect(page.getByRole('button',{name:'备用网页登录',exact:true})).toBeDisabled();
  await expect(page.getByRole('button',{name:'停止读取',exact:true})).toBeEnabled();
  await update({authState:'connected',quotaState:'ready',remaining:69,quotaWindows:[{label:'个人 Auto 月度剩余',remaining:69,resetsAt:null},{label:'个人 API 月度剩余',remaining:31,resetsAt:null}],canDisconnect:true},5);
  await expect(page.locator('.pd-quota-card strong')).toHaveText(['69%','31%']);
  await expect(page.locator('.pd-panel')).not.toContainText('周剩余');
  await page.getByRole('button',{name:'停止读取',exact:true}).click();
  expect(await page.evaluate(()=>window.__pulseTest.sent.some(message=>message.type==='disconnect-account'&&message.applicationId==='cursor'))).toBe(true);
  await update({readMode:'off',quotaState:'unavailable',authState:'signed-out'},6);
  await expect(page.getByRole('button',{name:'刷新',exact:true})).toHaveCount(0);
  await page.getByRole('button',{name:'恢复自动读取',exact:true}).click();
  expect(await page.evaluate(()=>window.__pulseTest.sent.some(message=>message.type==='resume-auto'&&message.applicationId==='cursor'))).toBe(true);
  await update({readMode:'auto',quotaState:'loading'},7);
  await expect(page.getByRole('button',{name:'备用网页登录',exact:true})).toHaveCount(0);
  await expect(page.locator('.pd-quota-card')).toContainText('正在自动读取');
  await update({readMode:'auto',quotaSource:'desktop-session',authState:'connected',quotaState:'ready',remaining:69,quotaWindows:[{label:'个人月度剩余',remaining:69,resetsAt:null}],canDisconnect:true},8);
  await expect(page.locator('.pd-panel-footer')).toContainText('桌面登录 · 只读');
  await expect(page.getByRole('button',{name:'备用网页登录',exact:true})).toHaveCount(0);
  await page.locator('.pd-dock').screenshot({path:join(tmpdir(),`pulse-auto-read-${viewport.width}.png`)});
  await page.getByRole('button',{name:'下一组应用',exact:true}).click();
  await expect(page.locator('.pd-summary')).toHaveCount(3);
  await page.locator('[data-application="kimi"].pd-summary').focus();await page.keyboard.press('Enter');
  await expect(page.locator('.pd-panel')).toContainText('此产品额度尚未接入');
  await expect(page.getByRole('button',{name:'备用网页登录',exact:true})).toHaveCount(0);
  await page.getByRole('button',{name:'下一组应用',exact:true}).click();
  await expect(page.locator('.pd-summary')).toHaveCount(2);
  await expect(page.locator('.pd-panel h2')).toHaveText('豆包工作');
  await page.getByRole('button',{name:'下一组应用',exact:true}).click();
  await page.locator('[data-application="claude"].pd-summary').focus();await page.keyboard.press('Enter');
  await expect(page.locator('.pd-panel')).toContainText('user:profile');
  const bounds=await page.locator('.pd-panel').boundingBox();expect(bounds.y+bounds.height).toBeLessThanOrEqual(566);
  const sizes=await page.evaluate(()=>window.__pulseTest.sent.filter(message=>message.type==='size'));
  expect(sizes.at(-1).panelOffset).toBe(152);expect(sizes.at(-1).railHeight).toBe(286);
  await page.screenshot({path:join(tmpdir(),`pulse-accounts-${viewport.width}.png`)});
  await page.getByRole('button',{name:'取消固定面板',exact:true}).click();
  await page.mouse.move(380,700);
  await expect(page.locator('.pd-dock')).toHaveAttribute('data-mode','compact');
  await expect(page.locator('vite-error-overlay')).toHaveCount(0);expect(errors).toEqual([]);
});
