import type {JSX} from "react";
import * as Quiet from "../../systems/quiet-workspace/web/index.js";
export const QuietExample:JSX.Element=<Quiet.QuietShell brand="示例" navigation={[{id:"tasks",label:"任务"}]} activeId="tasks" title="工作台"><Quiet.QuietDataTable rows={[{id:"1",name:"任务",amount:1}]} columns={[{key:"name",label:"任务"},{key:"amount",label:"用量",render:(value,row)=>String(value)+row.name}]} onRowActivate={row=>void row.name}/><Quiet.QuietDateRange label="日期" value={{start:"",end:""}} onChange={range=>void range.start}/><Quiet.QuietMultiSelect label="筛选" options={[]} value={[]} onChange={value=>void value.length}/><Quiet.QuietDrawer open={false} onOpenChange={()=>{}} title="详情"><Quiet.QuietProgress label="进度" value={0}/></Quiet.QuietDrawer></Quiet.QuietShell>;
import * as Ledger from "../../systems/midnight-ledger/web/index.js";
export const LedgerExample:JSX.Element=<Ledger.LedgerShell brand="示例" navigation={[{id:"tasks",label:"任务"}]} activeId="tasks" title="工作台"><Ledger.LedgerDataTable rows={[{id:"1",name:"任务",amount:1}]} columns={[{key:"name",label:"任务"},{key:"amount",label:"用量",render:(value,row)=>String(value)+row.name}]} onRowActivate={row=>void row.name}/><Ledger.LedgerDateRange label="日期" value={{start:"",end:""}} onChange={range=>void range.start}/><Ledger.LedgerMultiSelect label="筛选" options={[]} value={[]} onChange={value=>void value.length}/><Ledger.LedgerDrawer open={false} onOpenChange={()=>{}} title="详情"><Ledger.LedgerProgress label="进度" value={0}/></Ledger.LedgerDrawer></Ledger.LedgerShell>;
import * as Clear from "../../systems/clearline-console/web/index.js";
export const ClearExample:JSX.Element=<Clear.ClearShell brand="示例" navigation={[{id:"tasks",label:"任务"}]} activeId="tasks" title="工作台"><Clear.ClearDataTable rows={[{id:"1",name:"任务",amount:1}]} columns={[{key:"name",label:"任务"},{key:"amount",label:"用量",render:(value,row)=>String(value)+row.name}]} onRowActivate={row=>void row.name}/><Clear.ClearDateRange label="日期" value={{start:"",end:""}} onChange={range=>void range.start}/><Clear.ClearMultiSelect label="筛选" options={[]} value={[]} onChange={value=>void value.length}/><Clear.ClearDrawer open={false} onOpenChange={()=>{}} title="详情"><Clear.ClearProgress label="进度" value={0}/></Clear.ClearDrawer></Clear.ClearShell>;
import * as Signal from "../../systems/signal-studio/web/index.js";
export const SignalExample:JSX.Element=<Signal.SignalShell brand="示例" navigation={[{id:"tasks",label:"任务"}]} activeId="tasks" title="工作台"><Signal.SignalDataTable rows={[{id:"1",name:"任务",amount:1}]} columns={[{key:"name",label:"任务"},{key:"amount",label:"用量",render:(value,row)=>String(value)+row.name}]} onRowActivate={row=>void row.name}/><Signal.SignalDateRange label="日期" value={{start:"",end:""}} onChange={range=>void range.start}/><Signal.SignalMultiSelect label="筛选" options={[]} value={[]} onChange={value=>void value.length}/><Signal.SignalDrawer open={false} onOpenChange={()=>{}} title="详情"><Signal.SignalProgress label="进度" value={0}/></Signal.SignalDrawer></Signal.SignalShell>;
