import { useId, useRef } from 'react';
import { SpinnerGap, WarningCircle } from '@phosphor-icons/react';

export function DialogueButton({children,variant='primary',loading=false,disabled=false,error,onClick,className='',...props}) {
  // WebKit 的鼠标点击不默认聚焦按钮；显式聚焦让弹窗关闭后可恢复到触发控件。
  return <button {...props} type={props.type ?? 'button'} className={`du-button du-button--${variant} ${className}`} disabled={disabled || loading} aria-busy={loading || undefined} aria-invalid={!!error || undefined} onClick={event=>{event.currentTarget.focus({preventScroll:true});onClick?.(event);}}>{loading && <SpinnerGap className="du-spin" aria-hidden="true"/>}{error && <WarningCircle aria-hidden="true"/>}{children}{loading && <span className="du-sr">，正在处理</span>}</button>;
}
export function DialogueIconButton({icon:Icon,label,...props}) { return <DialogueButton {...props} variant={props.variant ?? 'ghost'} className="du-icon-button" aria-label={label} title={label}>{Icon && <Icon size={19} aria-hidden="true"/>}</DialogueButton>; }

function FieldFrame({label,hint,error,children,id,loading}) {return <div className="du-field"><label htmlFor={id}>{label}</label>{children}{loading && <small role="status">正在加载…</small>}{(error || hint) && <small id={`${id}-help`} role={error ? 'alert' : undefined} className={error ? 'du-error' : ''}>{error || hint}</small>}</div>;}
export function DialogueField({label,hint,error,loading,disabled,id:given,...props}) {
  const generated=useId(),id=given ?? generated;
  return <FieldFrame {...{id,label,hint,error,loading}}><input {...props} id={id} className="du-input" disabled={disabled || loading} aria-busy={loading || undefined} aria-invalid={!!error} aria-describedby={error || hint ? `${id}-help` : undefined}/></FieldFrame>;
}
export function DialogueTextarea({label,hint,error,loading,disabled,id:given,...props}) {
  const generated=useId(),id=given ?? generated;
  return <FieldFrame {...{id,label,hint,error,loading}}><textarea rows={3} {...props} id={id} className="du-input" disabled={disabled || loading} aria-busy={loading || undefined} aria-invalid={!!error} aria-describedby={error || hint ? `${id}-help` : undefined}/></FieldFrame>;
}
export function DialogueSelect({label,options,error,hint,loading,disabled,id:given,...props}) {
  const generated=useId(),id=given ?? generated;
  return <FieldFrame {...{id,label,hint,error,loading}}><select {...props} id={id} className="du-input" disabled={disabled || loading} aria-busy={loading || undefined} aria-invalid={!!error} aria-describedby={error || hint ? `${id}-help` : undefined}>{options.map(option=><option key={option.value} value={option.value} disabled={option.disabled}>{option.label}</option>)}</select></FieldFrame>;
}
export function DialogueToggle({label,checked,onChange,disabled,loading,error}) {return <div className="du-choice"><label><input type="checkbox" role="switch" checked={checked} onChange={event=>onChange?.(event.target.checked)} disabled={disabled || loading} aria-busy={loading || undefined} aria-invalid={!!error}/><span className="du-switch" aria-hidden="true"/><span>{label}</span></label>{loading && <small role="status">正在更新…</small>}{error && <small role="alert" className="du-error">{error}</small>}</div>;}
export function DialogueCheckbox({label,checked,onChange,disabled,loading,error}) {return <div className="du-choice"><label><input type="checkbox" checked={checked} onChange={event=>onChange?.(event.target.checked)} disabled={disabled || loading} aria-busy={loading || undefined} aria-invalid={!!error}/><span>{label}</span></label>{loading && <small role="status">正在更新…</small>}{error && <small role="alert" className="du-error">{error}</small>}</div>;}
export function DialogueSlider({label,value,onChange,min=0,max=100,step=1,unit='',disabled,loading,error,hint}) {
  const id=useId(); return <FieldFrame {...{id,label,hint,error,loading}}><div className="du-slider"><input id={id} type="range" min={min} max={max} step={step} value={value} disabled={disabled || loading} aria-invalid={!!error} aria-busy={loading || undefined} aria-describedby={error || hint ? `${id}-help` : undefined} aria-valuetext={`${value}${unit}`} onChange={event=>onChange?.(Number(event.target.value))}/><output htmlFor={id}>{value}{unit}</output></div></FieldFrame>;
}
export function DialogueSegmentedControl({label='显示方式',options,value,onChange,disabled}) {const name=useId();return <fieldset className="du-segmented" disabled={disabled}><legend className="du-sr">{label}</legend>{options.map(option=><label key={option.value}><input type="radio" name={name} checked={value===option.value} disabled={option.disabled} onChange={()=>onChange?.(option.value)} onKeyDown={event=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(event.key))return;event.preventDefault();const choices=options.filter(item=>!item.disabled),i=choices.findIndex(item=>item.value===value),next=event.key==='Home'?0:event.key==='End'?choices.length-1:(i+(event.key==='ArrowRight'?1:-1)+choices.length)%choices.length;onChange?.(choices[next].value);const inputs=[...event.currentTarget.closest('fieldset').querySelectorAll('input:not(:disabled)')];inputs[next]?.focus();}} tabIndex={value===option.value?0:-1}/><span>{option.label}</span></label>)}</fieldset>;}
export function DialogueTabs({items,value,onChange,disabled}) {
  const id=useId(),ref=useRef(null),active=items.find(item=>item.id===value) ?? items[0];
  return <div className="du-tabs"><div role="tablist" aria-label="内容视图" ref={ref}>{items.map((item,index)=><button type="button" role="tab" id={`${id}-${index}`} aria-controls={`${id}-panel`} aria-selected={active?.id===item.id} tabIndex={active?.id===item.id?0:-1} disabled={disabled || item.disabled} key={item.id} onClick={()=>onChange?.(item.id)} onKeyDown={event=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(event.key))return;event.preventDefault();const enabled=items.filter(i=>!i.disabled),current=enabled.findIndex(i=>i.id===item.id),next=event.key==='Home'?enabled[0]:event.key==='End'?enabled.at(-1):enabled[(current+(event.key==='ArrowRight'?1:-1)+enabled.length)%enabled.length];onChange?.(next.id);ref.current.querySelectorAll('button')[items.indexOf(next)]?.focus();}}>{item.label}</button>)}</div><div role="tabpanel" id={`${id}-panel`} aria-labelledby={`${id}-${items.indexOf(active)}`} tabIndex={0}>{active?.content}</div></div>;
}
export function DialogueBadge({children,tone='neutral'}) {return <span className={`du-badge du-badge--${tone}`}>{children}</span>;}
export function DialogueCard({title,description,action,children}) {return <section className="du-card">{(title || action) && <header><div><h3>{title}</h3>{description && <p>{description}</p>}</div>{action}</header>}{children}</section>;}
export function DialogueProgress({label,value,max=100}) {return <div className="du-progress"><span>{label}</span><progress aria-label={label} value={value==null ? undefined : Math.max(0,Math.min(max,value))} max={max}/>{value!=null && <small>{Math.round(value/max*100)}%</small>}</div>;}
export function DialogueEmptyState({title='暂无内容',description,actionLabel,onAction}) {return <div className="du-empty"><h3>{title}</h3><p>{description}</p>{actionLabel && <DialogueButton onClick={onAction}>{actionLabel}</DialogueButton>}</div>;}
export function DialogueNotification({title,description,tone='info',actionLabel,onAction}) {return <div className={`du-notification du-notification--${tone}`} role={tone==='error'?'alert':'status'}><WarningCircle size={20} aria-hidden="true"/><div><strong>{title}</strong><p>{description}</p></div>{actionLabel && <DialogueButton variant="secondary" onClick={onAction}>{actionLabel}</DialogueButton>}</div>;}
