import { Bell, FolderOpen, FloppyDisk, Gear, Plus } from "@phosphor-icons/react";
import { useState } from "react";
import { GalleryBlock, SectionHeader } from "../../../src/gallery/SectionHeader.jsx";
import { LedgerButton, LedgerDialog, LedgerEmptyState, LedgerField, LedgerIconButton, LedgerLineChart, LedgerMetric, LedgerNotification, LedgerPanel, LedgerSelect, LedgerStatusBadge, LedgerTable, LedgerToggle, ledgerInteractionStates } from "../web/index.js";
import { StateCell, StateGrid, StateSelector } from "./ShowcaseParts.jsx";

const marketOptions = [{ value: "us", label: "美股" }, { value: "hk", label: "港股" }, { value: "crypto", label: "加密货币" }];
const columns = [{ key: "symbol", label: "标的" }, { key: "market", label: "市场" }, { key: "price", label: "现价", align: "end" }, { key: "pnl", label: "收益", align: "end", render: (value) => <strong data-tone={value.startsWith("+") ? "positive" : "negative"}>{value}</strong> }];
const rows = [{ id: 1, symbol: "NVDA", market: "美股", price: "$134.23", pnl: "+4.52%", state: "hover" }, { id: 2, symbol: "TSLA", market: "美股", price: "$244.84", pnl: "-1.39%", state: "focus" }, { id: 3, symbol: "SPY 545P", market: "期权", price: "$3.42", pnl: "-16.65%", disabled: true }];

export function ComponentsGallery({ density, onNotify }) {
  const [dialogOpen, setDialogOpen] = useState(false); const [dialogState, setDialogState] = useState("default"); const [tableState, setTableState] = useState("default"); const [toggle, setToggle] = useState(true);
  return <><SectionHeader eyebrow="COMPONENTS · 7-STATE CONTRACT" title="组件与完整状态" description="14 个组件共享七态合同；容器状态通过所属控件或数据行表达。" aside={<span className="ml-component-density">{density === "compact" ? "紧凑" : "舒适"} · 14 components</span>} />
    <div className="ml-state-contract"><strong>固定状态顺序</strong>{ledgerInteractionStates.map((state) => <span key={state}>{state}</span>)}</div>
    <GalleryBlock eyebrow="ACTIONS" title="按钮七态"><StateGrid>{ledgerInteractionStates.map((state) => <StateCell state={state} key={state}><LedgerButton visualState={state} disabled={state === "disabled"} loading={state === "loading"} error={state === "error"} icon={FloppyDisk}>执行计划</LedgerButton></StateCell>)}</StateGrid><div className="ml-component-row"><LedgerButton icon={Plus}>新建计划</LedgerButton><LedgerButton variant="secondary" icon={Bell}>设置提醒</LedgerButton><LedgerButton variant="ghost">查看详情</LedgerButton><LedgerButton variant="danger">停止策略</LedgerButton>{ledgerInteractionStates.slice(0,4).map((state) => <LedgerIconButton key={state} label={`设置 ${state}`} icon={Gear} visualState={state} />)}</div></GalleryBlock>
    <GalleryBlock eyebrow="FORM" title="输入、选择与开关"><div className="ml-component-form"><LedgerField label="计划名称" defaultValue="趋势突破 3m" hint="最多 32 个字符" /><LedgerSelect label="交易市场" options={marketOptions} defaultValue="us" hint="决定价格与交易时段" /><LedgerToggle checked={toggle} onChange={setToggle} label="自动执行" description="只在风险校验通过后下单" /></div><StateGrid>{ledgerInteractionStates.map((state) => <StateCell state={state} key={state}><LedgerField label="止损比例" defaultValue="2.5%" visualState={state} disabled={state === "disabled"} loading={state === "loading"} error={state === "error" ? "必须介于 0.1% 与 20%" : undefined} /></StateCell>)}</StateGrid></GalleryBlock>
    <div className="ml-component-split"><GalleryBlock eyebrow="STATUS" title="标签与指标"><div className="ml-component-stack"><div className="ml-component-row"><LedgerStatusBadge tone="positive" dot>盈利</LedgerStatusBadge><LedgerStatusBadge tone="negative" dot>亏损</LedgerStatusBadge><LedgerStatusBadge tone="warning">临近到期</LedgerStatusBadge><LedgerStatusBadge tone="info">ETF</LedgerStatusBadge><LedgerStatusBadge tone="option">期权</LedgerStatusBadge></div><div className="ml-metric-row"><LedgerMetric label="累计收益率" value="+31.8%" delta="较上月 +2.4%" tone="positive" /><LedgerMetric label="最大回撤" value="-4.3%" delta="风险受控" tone="negative" /><LedgerMetric label="运行天数" value="217" /></div></div></GalleryBlock><GalleryBlock eyebrow="PANEL" title="面板状态"><LedgerPanel title="风险预算" action={<LedgerStatusBadge tone="positive">通过</LedgerStatusBadge>}><p className="ml-panel-copy">当前计划占用总风险预算的 18%，仍在目标范围内。</p></LedgerPanel></GalleryBlock></div>
    <GalleryBlock eyebrow="DATA" title="表格"><StateSelector value={tableState} onChange={setTableState} states={["default", "loading", "error", "empty"]} /><LedgerTable caption="当前持仓" columns={columns} rows={tableState === "empty" ? [] : rows} state={tableState} onRetry={() => setTableState("loading")} onRowActivate={(row) => onNotify?.(`已选择 ${row.symbol}`)} /></GalleryBlock>
    <GalleryBlock eyebrow="CHART" title="折线图状态"><div className="ml-chart-state-grid"><article><header><strong>默认</strong><small>DEFAULT</small></header><LedgerLineChart title="示例活跃量" data={[8,12,14,18,17,21,24]} unit="次" description="演示数据" /></article><article><header><strong>加载</strong><small>LOADING</small></header><LedgerLineChart state="loading" /></article><article><header><strong>错误</strong><small>ERROR</small></header><LedgerLineChart state="error" onRetry={() => onNotify?.("已请求重新加载行情")} /></article></div></GalleryBlock>
    <GalleryBlock eyebrow="OVERLAY" title="对话框"><div className="ml-component-row"><StateSelector value={dialogState} onChange={setDialogState} states={["default", "loading", "error", "disabled"]} /><LedgerButton onClick={() => setDialogOpen(true)}>打开交易确认</LedgerButton></div><LedgerDialog open={dialogOpen} onOpenChange={setDialogOpen} title="确认执行计划" description="订单将在风险校验通过后提交。" loading={dialogState === "loading"} disabled={dialogState === "disabled"} error={dialogState === "error" ? "行情数据已过期，请刷新后重试。" : undefined} actions={<><LedgerButton variant="ghost" onClick={() => setDialogOpen(false)}>取消</LedgerButton><LedgerButton disabled={dialogState === "disabled"} loading={dialogState === "loading"} onClick={() => { onNotify?.("计划已提交"); setDialogOpen(false); }}>确认执行</LedgerButton></>}><p>NVDA · 买入 10 股 · 限价 $134.20</p></LedgerDialog></GalleryBlock>
    <GalleryBlock eyebrow="FEEDBACK" title="通知与空状态"><div className="ml-feedback-grid"><LedgerNotification tone="success" title="计划已执行" description="NVDA 买单已成交 10 股。" actionLabel="查看订单" /><LedgerNotification tone="warning" title="期权临近到期" description="NVDA 150C 距到期还有 5 天。" /><LedgerNotification error title="行情连接中断" description="新订单暂时无法提交。" actionLabel="重新连接" /><LedgerNotification loading title="正在同步持仓" description="完成后自动更新盈亏。" /></div><LedgerEmptyState icon={FolderOpen} title="还没有交易计划" description="创建第一条计划后，执行状态和历史记录会显示在这里。" actionLabel="新建计划" onAction={() => onNotify?.("正在创建交易计划")} /></GalleryBlock></>;
}
